# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '119ae78c-3cba-4b06-a76b-8f318ef90d3a'
  imageRepository: 'demo'
  containerRegistry: 'czyacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/src/order-service/Dockerfile'
  tag: '$(Build.BuildId)'


stages:
- stage: Build
  displayName: Build and publish stage
  jobs:
  - job: Build
    displayName: Build job
    pool:
      name: 'self-hosted-linux'
    steps:
    - task: Docker@2
      displayName: Build and publish image to Azure Container Registry
      inputs:
        command: buildAndPush
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
