# Docker
# Deploy the app to AKS
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '119ae78c-3cba-4b06-a76b-8f318ef90d3a'
  imageRepository: 'demo'
  containerRegistry: 'czyacr.azurecr.io'
  tag: '$(Build.BuildId)'

  # Agent Pool name
  vmPoolName: 'self-hosted-linux'

stages:

- stage: Deploy
  displayName: Deploy stage
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      name: $(vmPoolName)
    environment: 'dev.spot'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                mkdir -p $(Pipeline.Workspace)/manifests
                
                curl -o $(Pipeline.Workspace)/manifests/aks-store-all-in-one.yaml https://raw.githubusercontent.com/v-zhiyuchen/aks-store-demo/refs/heads/main/aks-store-all-in-one.yaml
          # - task: KubernetesManifest@0
          #   displayName: Deploy to Kubernetes cluster
          #   inputs:
          #     action: 'deploy'
          #     kubernetesServiceConnection: 'dev-akstest-spot-1735878886457'
          #     namespace: 'spot'
          #     manifests: '$(Pipeline.Workspace)/manifests/aks-store-all-in-one.yaml'
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: 'delete'
              kubernetesServiceConnection: 'dev-akstest-spot-1735878886457'
              namespace: 'spot'
              arguments: '-f $(Pipeline.Workspace)/manifests/aks-store-all-in-one.yaml'